name: 'Deploy to S3'
description: 'Builds and deploys to S3'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  s3-bucket-name:
    description: 'S3 Bucket Name'
    required: true
  cloudfront-distribution-id:
    description: 'CloudFront Distribution ID'
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Build
      shell: bash
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Sync to S3
      shell: bash
      run: |
        aws s3 sync ./build s3://${{ inputs.s3-bucket-name }}/ --delete

    - name: Invalidate CloudFront
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution-id }} --paths "/*"
